### ISSUE TITLE
[1.4][Existing Save] Crash on 'U' press

### ISSUE THREAD

**Issue by oliverbutler** [tburrows13/SpidertronEnhancements#2]
**Reproduce**
- Existing world
- Factorio v1.1.27
- Fresh install of v1.4

I'll take a look at the source now, but leaving this here.

**Screenshot**
![Screenshot 2021-03-24 145726](https://user-images.githubusercontent.com/47489826/112332140-682fdf80-8cb1-11eb-84b2-04d6b0f4d670.png)

**Comment by tburrows13** [comment]
No worries, I've got a fix for that coming now!

**Comment by tburrows13** [comment]
Thanks very much for the report, I'd removed the no longer-needed global but I forgot to remove that one reference to it. Fixed now in 1.4.1.
