### ISSUE TITLE
possible clash with vehiclehud_0.0.9 mod

### ISSUE THREAD

**Issue by angrypidgeon123** [tburrows13/SpidertronEnhancements#4]
The mod Spidertron Enhancements (1.9.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event SpidertronEnhancements::spidertron-enhancements-enter-vehicles (ID 461)
The mod HUDs for vehicles (0.0.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event vehiclehud::on_player_driving_changed_state (ID 28)
__vehiclehud__/control.lua:411: attempt to index field 'train' (a nil value)
stack traceback:
	__vehiclehud__/control.lua:411: in function 'showVehicleStats'
	__vehiclehud__/control.lua:470: in function <__vehiclehud__/control.lua:462>
stack traceback:
	[C]: in function 'set_driver'
	__SpidertronEnhancements__/scripts/spidertron_lib.lua:378: in function 'deserialise_spidertron'
	__SpidertronEnhancements__/scripts/hidden-spidertron.lua:244: in function 'enter_spidertron'
	__SpidertronEnhancements__/scripts/hidden-spidertron.lua:336: in function 'enter_vehicles_pressed'
	__SpidertronEnhancements__/scripts/hidden-spidertron.lua:411: in function <__SpidertronEnhancements__/scripts/hidden-spidertron.lua:409>

**Comment by tburrows13** [comment]
Thanks for the report, however since the crash occurs in vehiclehud, there's nothing I can do about this, sorry.
